#!/bin/bash
# required in inputfile for smp 4:

#$ -pe smp 1
#$ -m ae
#$ -r n
#$ -M mcarlozo@nd.edu
#$ -q long@@maginn
#$ -N opt_gp

export PATH=/afs/crc.nd.edu/user/m/mcarlozo/.conda/envs/hfcs-fffit/bin:$PATH

export  INPUT=$1
python3  ${INPUT}
